export const players = [
  {
    external_player_id: "wgyqjCcYRoistNUSfZgYLQ",
    name: "CerberoS",
    region: "EU",
    fame: 1000000n,
    killFame: 275380299n,
    deathFame: 171172046n,
    rating: 85,
    stars: 4,
  },
  {
    external_player_id: "KgXzr2H7RF2PcYKr1uJGQA",
    name: "cephes",
    region: "EU",
    fame: 1500000n,
    killFame: 97676701n,
    deathFame: 93787909n,
    rating: 90,
    stars: 5,
  },
  {
    external_player_id: "5N33rMGDQH-LjQghZumvoA",
    name: "Phildas",
    region: "EU",
    fame: 2000000n,
    killFame: 161168899n,
    deathFame: 109544331n,
    rating: 95,
    stars: 5,
  },
  {
    external_player_id: "JLz63ANFSKyZ9ufMvTx_ow",
    name: "RuskiePlacki",
    region: "EU",
    fame: 0n,
    killFame: 0n,
    deathFame: 0n,
    rating: 0,
    stars: 0,
  },
  {
    external_player_id: "JGIl2brARpaMppTge_1ViA",
    name: "Yazdaa",
    region: "EU",
    fame: 0n,
    killFame: 0n,
    deathFame: 0n,
    rating: 0,
    stars: 0,
  },
  {
    external_player_id: "5SZHj1-bQBWIeX_rd7wshA",
    name: "cukson",
    region: "EU",
    fame: 0n,
    killFame: 0n,
    deathFame: 0n,
    rating: 0,
    stars: 0,
  },
  {
    external_player_id: "EtKrtOAsSOuR1bd4KrCNSQ",
    name: "gromalol",
    region: "EU",
    fame: 0n,
    killFame: 0n,
    deathFame: 0n,
    rating: 0,
    stars: 0,
  },
]
