export const VERSION = "0.0.0";

// Shared ESLint flat-config entries land here as packages grow lint scripts.
// apps/web keeps the eslint config generated by create-next-app.
export const config = [];
